apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/glusterfs
parameters:
  gidMax: "50000"
  gidMin: "40000"
  resturl: http://192.168.0.132:9999
  volumetype: replicate:2
  restauthenabled: "false"
