replicaCount: 1
image:
  repository: 192.168.0.132:1443/library/mobile:2.0.0
  pullPolicy: Always
  secrets: harborsecret
service:
  enabled: true
  name: mobile-stable
  type: ClusterIP
  containerPort: 80
  routeHost: mobile.ckmro.com
# configMap:
# resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
