apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: glusterfs-cluster
    path: "gv5"
    readOnly: false
