namespace: dev
replicaCount: 1
image:
  repository: 192.168.0.132:1443/incubator/gateway:latest
  pullPolicy: Always
service:
  enabled: true
  name: gateway
  type: ClusterIP
  containerPort: 7701
  routeHost: dev.gateway.ckmro.com
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
