apiVersion: v1
kind: Service
metadata:
  name: {{ template "activemq.fullname" . }}
  labels:
    app: {{ template "activemq.name" . }}
    chart: {{ template "activemq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: jms
      protocol: TCP
      name: jms
  selector:
    app: {{ template "activemq.name" . }}
    release: {{ .Release.Name }}
