replicaCount: 1
image:
  repository: registry.ckmro.com:1443/library/customer:2.0.0
  pullPolicy: Always
  profile: prod
service:
  enabled: true
  name: customer
  type: ClusterIP
  containerPort: 7201
  # routeHost: dev.customer.ckmro.com
cbit:
  config: /etc/cbit/config-server_prod.yml
volume:
  path: /data/gfs
configMap:
resources: