namespace: dev
replicaCount: 1
image:
  repository: 192.168.0.132:1443/incubator/aggregations:latest
  pullPolicy: Always
  profile: dev
service:
  enabled: true
  name: aggregations
  type: ClusterIP
  containerPort: 8082
  routeHost: dev.aggregations.ckmro.com
configMap:
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
