namespace: dev
replicaCount: 1
image:
  repository: 192.168.0.132:1443/incubator/member:latest
  pullPolicy: Always
  profile: dev
service:
  enabled: true
  name: member
  type: ClusterIP
  containerPort: 6601
  routeHost: dev.member.ckmro.com
configMap:
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
