kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: "jenkins"
  volumeName: jenkins-dev-volume
