apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-dev-volume
  namespace: kube-system
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "gv6"
    readOnly: false
