apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-dev-volume
  labels:
    name: jenkins
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "gv5" # Need create it by glusterfs first.
    readOnly: false
