namespace: dev
replicaCount: 1
image:
  repository: 192.168.0.132:1443/incubator/basic:latest
  pullPolicy: Always
  profile: dev
service:
  enabled: true
  name: basic
  type: ClusterIP
  containerPort: 6901
  routeHost: dev.basic.ckmro.com
configMap:
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
