namespace: dev
replicaCount: 1
image:
  repository: rmohr/activemq
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 61616

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - dev.activemq.ckmro.com
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
