apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    k8s-app: "{{ .Chart.Name }}"
  ports:
  - name: http
    targetPort: "{{ .Values.service.containerPort }}"
    port: "{{ .Values.service.containerPort }}" 
