apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "traefik-{{ .Chart.Name }}-route"
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.service.routeHost }}
    http:
      paths:
      - path:
        backend:
          serviceName: "{{ .Values.service.name }}"
          servicePort: 7101
