apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-route
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.service.routeHost }}
    http:
      paths:
      - path:
        backend:
          serviceName: "{{ .Chart.Name }}-incubator-svc"
          servicePort: 80
