namespace: dev
replicaCount: 1
image:
  repository: 192.168.0.132:1443/incubator/common:latest
  pullPolicy: Always
service:
  enabled: true
  name: common
  type: ClusterIP
  containerPort: 7101
  routeHost: dev.common.ckmro.com
configMap:
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
