replicaCount: 1
image:
  repository: registry.ckmro.com:1443/library/auth:2.0.0
  pullPolicy: Always
  secrets: harborsecret
service:
  enabled: true
  name: accounts-stable
  type: ClusterIP
  containerPort: 9997
  routeHost: accounts.ckmro.com
configMap:
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
