namespace: dev
replicaCount: 1
image:
  repository: 192.168.0.132:1443/incubator/customer:latest
  pullPolicy: Always
  profile: dev
service:
  enabled: true
  name: customer
  type: ClusterIP
  containerPort: 7201
  routeHost: dev.customer.ckmro.com
cbit:
  config: /etc/cbit/config-server.yml
volume:
  path: /data/brick1/gv0
configMap:
resources: