namespace: dev
image:
  repository: "kibana"
  tag: "4.5.4"
  pullPolicy: "IfNotPresent"

commandline:
  args:

env:
  ELASTICSEARCH_URL: http://192.168.0.131:9200
  SERVER_PORT: 5601

service:
  type: ClusterIP
  internalPort: 5601
  annotations:
ingress:
  enabled: true
  hosts: dev.kibana.ckmro.com
resources: {}
tolerations: []
nodeSelector: {}
podAnnotations: {}
replicaCount: 1
